events {}

http {

    upstream backend {
        server auth-service:8080;
        server user-service:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://backend;
        }
    }
}